sudo: required
language: node_js
env:
  - JASMINE_BROWSER=firefox
node_js:
  - "0.12"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - curl https://install.meteor.com/ | sh
