sudo: required
language: node_js
node_js:
  - "0.12"
before_install:
  - export DISPLAY=:99.0
  - export JASMINE_BROWSER=Firefox
  - sh -e /etc/init.d/xvfb start
  - curl https://install.meteor.com/ | sh
env:
 - JASMINE_BROWSER=Firefox